overrides:
  vite: "catalog:"
  vitest: "catalog:"

allowBuilds:
  msgpackr-extract: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.7
  vitest: 4.1.10
  vite-plus: 0.2.7
  "@vitest/coverage-v8": 4.1.10
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
minimumReleaseAgeExclude:
  - effect@4.0.0-beta.107
